### PR TITLE
Add 'hold' piece feature

### PR DESCRIPTION
**Pull request by paulsmith**
Tapping the CTRL key (left or right) will place the current piece in the
"hold" queue and set the current piece to the next piece. The hold piece
can then later be swapped with the current piece by tapping CTRL again.
This is a feature present in modern Tetrises.

The hold swap can only be executed once per falling piece.

### CODE REVIEW

**Comment by paulsmith** [comment]
> Why not let the player swap back and forth as many times as they want?

I'm basing the behavior on recent commercial Tetrises I've played - I think the reason is, because the hold/swap action resets the drop piece back to the top of the board, you could just keep hitting hold as a way to stall.

**Comment by andrewrk** [comment]
Ahh. That makes sense. Well I think for my subjective take on this game, I will have the swap feature not reset the drop piece to the top of the board, but allow any number of swaps. 

This can be merged though, I'll make that change later.

**Comment by markfirmware** [comment]
I moved a lot of main.zig into coretetris.zig. This made a lot of functions become members of Tetris:
https://github.com/markfirmware/tetris/blob/65e277a76c57a1b4100501ebbe5b5346587713ba/src/main.zig#L111-L115

**Comment by markfirmware** [comment]
GlfwTetris has an embedded Tetris and the members of Tetris that were glfw-specific:
https://github.com/markfirmware/tetris/blob/65e277a76c57a1b4100501ebbe5b5346587713ba/src/main.zig#L21-L27

**Pull request merged**
